app_login/urls.py
from django.conf.urls import url
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
url(r'^$', index, name='index'),
]

app_signup/urls.py
from django.conf.urls import url
from .views import index,regist

#url for app, add your URL Configuration

urlpatterns = [
url(r'^$', index, name='index'),
url(r'^index', index, name='index'),
url(r'^regist/$', regist, name='regist'),
]

database-project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_create.urls as app_create
import app_login.urls as login
import app_signup.urls as signup
import app_profile.urls as profile
import app_newsdraft.urls as newsdraft
import app_polldraft.urls as polldraft

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^create/', include(app_create, namespace='create')),
    url(r'^signup/', include(signup, namespace='signup')),
     url(r'^profile/', include(profile, namespace='profile')),
    url(r'^newsdraft/', include(newsdraft, namespace='newsdraft')),
    url(r'^polldraft/', include(polldraft, namespace='polldraft')),
    url(r'^$', RedirectView.as_view(url='login/',permanent='True')) #kalo perlu
]

app_signup/models.py
from django.db import models

# Create your models here.

class Pengguna(models.Model):
	username = models.CharField(max_length = 20, primary_key= True)
	password = models.CharField(max_length = 20)
	role = models.CharField(max_length = 20)
	
	class Meta:
		db_table = "Pengguna"
		
class Narasumber(models.Model):
	username = models.CharField(max_length = 20, primary_key= True)
	idNum = models.CharField(max_length=10) # anggepannya npm
	name = models.CharField(max_length=50)
	birthdate = models.CharField(max_length=10) #format: DD/MM/YYYY
	birthplace = models.CharField(max_length=20)
	email = models.EmailField()
	phone = models.CharField(max_length = 15)
	
	# tergantung role nya
	# status = models.CharField(max_length= 20, blank=True)
	# idUniv = models.IntegerField(blank=True) #ada 50 univ
	
	class Meta:
		db_table = "Narasumber"
		
		
# cekkk, perlu pake forms.py?

app_signup/forms.py
from django import forms

# Create your models here.

class PenggunaForm(forms.Form):
	username = forms.CharField(max_length = 20)
	password = forms.CharField(max_length = 20)
	role = forms.CharField(max_length = 20)
	
	class Meta:
		db_table = "Pengguna"
		
class NarasumberForm(forms.Form):
	idNum = forms.CharField(max_length=15) # anggepannya npm
	name = forms.CharField(max_length=50)
	# birthdate = forms.DateField()
	birthplace = forms.CharField(max_length=30)
	email = forms.EmailField()
	phone = forms.CharField(max_length = 15)
	
	# tergantung role nya
	# status = forms.CharField(max_length= 20)
	# idUniv = forms.IntegerField() #ada 50 univ
		
		
# cekkk, perlu pake forms.py?

app_signup/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotFound
from .models import Pengguna, Narasumber
from .forms import PenggunaForm, NarasumberForm

# Create your views here.
response = {}

def index(request):	
	html = 'signup.html'
	response['author'] = 'Kelompok 8'
	return render(request, html, response)

def regist(request):
	userform = PenggunaForm(request.POST or None)
	narsumform = NarasumberForm(request.POST or None)
	print("VALIDATOR: =========== "+str(userform.is_valid())+" narsum "+str(narsumform.is_valid()))
	if(request.method == 'POST' and userform.is_valid() and narsumform.is_valid()):
		response['username'] = request.POST['username']
		response['password'] = request.POST['password']
		response['idNum'] = request.POST['idNum']
		response['role'] = request.POST['role']
		response['name'] = request.POST['name']
		response['email'] = request.POST['email']
		response['phone'] = request.POST['phone']
		response['birthdate'] = request.POST['birthdate']
		response['birthplace'] = request.POST['birthplace']

		#ngesave ke database
		user = Pengguna(username=response['username'],password=response['password'],role=response['role'])
		narsum = Narasumber(username=response['username'],idNum=response['idNum'], name=response['name'], birthplace=response['birthplace'], birthdate=response['birthdate'], phone=response['phone'], email=response['email'])

		user.save()
		narsum.save()
		#ga pake additional atrribute

		return HttpResponseRedirect('/login/')
	return HttpResponseRedirect('/signup/')

app_signup/templates/signup.html
{% extends "layout/base.html" %}


{% block content %}
{% load static %}

<!-- <div class="signup container wrap-login100"> -->
<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
  <div class="signup container wrap-login100">
      <form action="{% url 'signup:regist' %}" method="POST">
        {% csrf_token %}
        <h1>Sign Up</h1>
        <legend><span class="number">1</span>Your basic info</legend>
        <fieldset>
        <label for="role" onchange="roleSignUp()">Role:</label>
        <select id="role" name="role">
          <option value="student">Mahasiswa</option>
          <option value="lecturer">Dosen</option>
          <option value="staff">Staff</option>
        </select>

          <label for="username">Username:</label>
          <input type="text" id="username" name="username">

          <label for="password">Password:</label>
          <input type="password" id="password" name="password">

          <label for="idNum">ID:</label>
          <input type="text" id="idNum" name="idNum">
        </fieldset>
        <fieldset>
          <legend><span class="number">2</span>Your Profile</legend>
          <label for="name">Nama:</label>
          <input type="text" id="name" name="name">


          <label for="birthdate">Tanggal Lahir:</label>
          <input type="text" id="birthdate" name="birthdate">
          <label for="birthplace">Tempat Lahir:</label>
          <input type="text" id="birthplace" name="birthplace">

          <label for="email">Email:</label>
          <input type="email" id="email" name="email">

          <label for="phone">No. Telepon:</label>
          <input type="text" id="phone" name="phone">
        </fieldset>

          <div id="additional"></div>
        <div class="row justify-content-center">
          <button type="submit" class="login100-form-btn">Sign Up</button>
        </div>
        <div class="row justify-content-center" style="color:black">
          <small style="text-align:center"><a href="/login/">Already have the account</a></small>
        </div>
      </form>
    </div>
</div>
{% endblock %}